### Send fetch songs request
GET http://localhost:3000/songs


### Find songs request
GET http://localhost:3000/songs/1


### Create new songs request
POST http://localhost:3000/songs
Content-Type: application/json

{
    "title": "RayeK",
    "artists": ["Hamza Namira", "Mohamed Emara"],
    "releaseDate": "2023-07-19",
    "duration": "03:48"
}

### Update songs request
PUT http://localhost:3000/songs/1


### Delete songs request 
DELETE http://localhost:3000/songs/1

### Get Hello
GET http://localhost:3000/songs
