### Send fetch songs request
GET http://localhost:8080/songs


### Find all songs request
GET http://localhost:8080/songs

### Find the second page of songs & 12 songs per page.
GET http://localhost:8080/songs/?page=2&limit=12

### Create new songs request
POST http://localhost:8080/songs
Content-Type: application/json

{
    "title": "Duet",
    "artists": [1, 2],
    "releaseDate": "2023-09-12",
    "duration": "03:45",
    "lyrics": "no lyrics provided"
}

### Update songs request
PUT http://localhost:8080/songs/6
Content-Type: application/json

{
    "lyrics": "This is an updated version of lyrics..."
}


### Delete songs request 
DELETE http://localhost:8080/songs/3

### Get Hello
GET http://localhost:8080/users



### Create new playlist
POST http://localhost:8080/playlists
Content-Type: application/json

{
    "name": "Raye2",
    "songs": [],
    "user": 1    
}

### Singup User:
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "firstName": "Mohamed",
    "lastName": "Emara",
    "email": "mohamedemara@gmail.com",
    "password": "1234"
}

### Login User:
POST http://localhost:8080/auth/login 
Content-Type: application/json

{
    "email": "emara@gmail.com",
    "password": "1234"
}

# Access Token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6Im1vaGFtZWRlbWFyYUBnbWFpbC5jb20iLCJzdWIiOjcsImlhdCI6MTcxMzUxNjg1MCwiZXhwIjoxNzE2MTA4ODUwfQ.ucsX2-t7gbFNDT3wye2paeQAs5UFyTt_DgGtRcIqHa0

### Profile      (UnAuthorized)
GET http://localhost:8080/profile


### Profile      (with Bearer access token)
GET http://localhost:8080/profile
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImVtYXJhQGdtYWlsLmNvbSIsInVzZXJJZCI6NCwiaWF0IjoxNzEzODg4NzAzLCJleHAiOjE3MTY0ODA3MDN9.hFuM_41peivIP2vN_sBjlZKPj2a1pAoCKkc13pwo6PM
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbWl5dXN1ZkBnbWFpbC5jb20iLCJ1c2VySWQiOjksImFydGlzdElkIjozLCJpYXQiOjE3MTM1NDExNzYsImV4cCI6MTcxNjEzMzE3Nn0.7r0oYPy6dcakEtYzxOn8XDOeGRGymGTYDx7YBaUuLbQ
### Create new song
POST http://localhost:8080/songs 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbWl5dXN1ZkBnbWFpbC5jb20iLCJ1c2VySWQiOjksImFydGlzdElkIjozLCJpYXQiOjE3MTM1NDExNzYsImV4cCI6MTcxNjEzMzE3Nn0.7r0oYPy6dcakEtYzxOn8XDOeGRGymGTYDx7YBaUuLbQ
Content-Type: application/json

{
    "title": "Worry Ends",
    "artists": [3],
    "releaseDate": "2010-08-21",
    "duration": "03:44",
    "lyrics": "UnAvailable"
}

### Enable 2FA
POST http://localhost:8080/auth/enable-2fa 
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbWl5dXN1ZkBnbWFpbC5jb20iLCJ1c2VySWQiOjksImFydGlzdElkIjozLCJpYXQiOjE3MTM1NDExNzYsImV4cCI6MTcxNjEzMzE3Nn0.7r0oYPy6dcakEtYzxOn8XDOeGRGymGTYDx7YBaUuLbQ
Content-Type: application/json


### Validate 2FA token
POST http://localhost:8080/auth/validate-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbWl5dXN1ZkBnbWFpbC5jb20iLCJ1c2VySWQiOjksImFydGlzdElkIjozLCJpYXQiOjE3MTM1NDExNzYsImV4cCI6MTcxNjEzMzE3Nn0.7r0oYPy6dcakEtYzxOn8XDOeGRGymGTYDx7YBaUuLbQ
Content-Type: application/json

{
    "token": "582583"
}



### Disable Two Factor Authentication
POST http://localhost:8080/auth/disable-2fa
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNhbWl5dXN1ZkBnbWFpbC5jb20iLCJ1c2VySWQiOjksImFydGlzdElkIjozLCJpYXQiOjE3MTM1NDExNzYsImV4cCI6MTcxNjEzMzE3Nn0.7r0oYPy6dcakEtYzxOn8XDOeGRGymGTYDx7YBaUuLbQ



### Create new user
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "firstName": "Maher",
    "lastName": "Zain",
    "email": "maherzain@gmail.com",
    "password": "1234",
    "phone": "134234234"
}

# apiKey = ba3f0fb2-bc10-4089-9b05-5c4bb73d2094

// Now we'll provide this apiKey to access profile route.

### Access Profile Route with API Key
GET http://localhost:8080/auth/profile
Authorization: Bearer ba3f0fb2-bc10-4089-9b05-5c4bb73d2094
