### Send fetch songs request
GET http://localhost:8080/songs


### Find all songs request
GET http://localhost:8080/songs

### Find the second page of songs & 12 songs per page.
GET http://localhost:8080/songs/?page=2&limit=12

### Create new songs request
POST http://localhost:8080/songs
Content-Type: application/json

{
    "title": "Duet",
    "artists": [1, 2],
    "releaseDate": "2023-09-12",
    "duration": "03:45",
    "lyrics": "no lyrics provided"
}

### Update songs request
PUT http://localhost:8080/songs/6
Content-Type: application/json

{
    "lyrics": "This is an updated version of lyrics..."
}


### Delete songs request 
DELETE http://localhost:8080/songs/3

### Get Hello
GET http://localhost:8080/users



### Create new playlist
POST http://localhost:8080/playlists
Content-Type: application/json

{
    "name": "Raye2",
    "songs": [],
    "user": 1    
}

### Singup User:
POST http://localhost:8080/auth/signup
Content-Type: application/json

{
    "firstName": "Mohamed",
    "lastName": "Emara",
    "email": "mohamedemara@gmail.com",
    "password": "1234"
}

### Login User:
POST http://localhost:8080/auth/login 
Content-Type: application/json

{
    "email": "mohamedemara@gmail.com",
    "password": "12344"
}