version: '3'

services:
  postgresdb:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: spotify-api
    volumes:
      - /private/var/lib/postgresql/spotify:/var/lib/postgresql
    ports:
      - "5432:5432"

  